#!/usr/bin/env python

import sys

pkg = 'vigir_plugin_manager'
widget = 'plugin_manager_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))
